### ISSUE TITLE
Reorganizare pentru clasa a 12-a

### ISSUE THREAD

**Issue by StormFireFox1** [StormFireFox1/Probleme-Info-11G#19]
Trebuie sa reorganizez directoarele astfel incat sa fie mai usor sa gasim materia pentru diversele clase.

**Comment by StormFireFox1** [comment]
Merci, @alexghergh pentru ajutor.

**Comment by alexghergh** [comment]
Oricand :+1:

**Comment by trulyronak** [comment]
Nice!
